name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  IMAGE_NAME: byr
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  GHCR_USERNAME: ${{ github.actor }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Log in to GitHub Container Registry (GHCR)
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ env.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Extract version from pyproject.toml
      id: get_version
      run: |
        version=$(grep '^version =' pyproject.toml | cut -d '"' -f2)
        echo "VERSION=v$version" >> $GITHUB_ENV
        echo "Version: v$version"

    - name: Build and push Docker image to DockerHub and GHCR
      run: |
        DOCKER_IMAGE=docker.io/${DOCKERHUB_USERNAME}/$IMAGE_NAME
        GHCR_IMAGE=ghcr.io/${GHCR_USERNAME}/$IMAGE_NAME

        docker build -t $DOCKER_IMAGE:$VERSION -t $GHCR_IMAGE:$VERSION .

        # Tag as latest
        docker tag $DOCKER_IMAGE:$VERSION $DOCKER_IMAGE:latest
        docker tag $GHCR_IMAGE:$VERSION $GHCR_IMAGE:latest

        # Push all tags
        docker push $DOCKER_IMAGE:$VERSION
        docker push $DOCKER_IMAGE:latest
        docker push $GHCR_IMAGE:$VERSION
        docker push $GHCR_IMAGE:latest
